# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rawmultiply <- function(m1, m2) {
    .Call('_EfficientTrace_rawmultiply', PACKAGE = 'EfficientTrace', m1, m2)
}

smartmultiply <- function(m1, m2, assistmat) {
    .Call('_EfficientTrace_smartmultiply', PACKAGE = 'EfficientTrace', m1, m2, assistmat)
}

